helmDefaults:
  atomic: true
  createNamespace: true
  cleanupOnFail: true
  timeout: 900
  force: true

repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: ingress-nginx
  url: https://kubernetes.github.io/ingress-nginx
- name: bitnami
  url: https://charts.bitnami.com/bitnami

releases:
  - name: ingress
    namespace: ingress
    chart: ingress-nginx/ingress-nginx
    installed: true
    values:
      - controller:
          extraArgs:
            enable-ssl-passthrough: ""
          hostNetwork: true
          kind: DaemonSet

  - name: metallb
    namespace: metallb-system
    chart: bitnami/metallb
    installed: true
    values:
      - configInline:
          address-pools:
          - name: default
            protocol: layer2
            addresses:
            - 172.17.0.1-172.17.255.255

  - name: metrics-server
    namespace: kube-system
    chart: bitnami/metrics-server
    installed: true
    values:
      - args:
        - --metric-resolution=60s
        - --kubelet-insecure-tls
        - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
