helmDefaults:
  atomic: true
  createNamespace: true
  cleanupOnFail: true
  timeout: 900
  force: true
  verify: false

templates:
  common: &common
    missingFileHandler: Warn
    values:
      - ./{{ .Release.Name }}.yaml.gotmpl
  stable: &stable
    <<: *common
    chart: stable/{{ .Release.Name }}
  bitnami: &bitnami
    <<: *common
    chart: bitnami/{{ .Release.Name }}
