helmDefaults:
  atomic: true
  timeout: 900
  tillerless: true

repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com/
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: kubernetes-dashboard
    url: https://kubernetes.github.io/dashboard

templates:
  common: &common
    missingFileHandler: Warn
    values:
      - ./{{ .Release.Name }}.yaml.gotmpl
  stable: &stable
    <<: *common
    chart: stable/{{ .Release.Name }}
  bitnami: &bitnami
    <<: *common
    chart: bitnami/{{ .Release.Name }}
